# File: Dockerfile.python
FROM ghcr.io/esuminski/node-iso
USER root
RUN apt update && apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
USER devuser
CMD [ "sleep", "infinity" ]